### ISSUE TITLE
RFC3986 'square brackets enclosed host' problem.

### ISSUE THREAD

**Issue by Parahexen** [httptoolkit/mockttp#44]
`TypeError [ERR_INVALID_URL] [ERR_INVALID_URL]: Invalid URL: http://[localhost:8123]
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at new URL (internal/url.js:330:22)
    at /_/httptoolkit-server/node_modules/mockttp/src/server/mockttp-server.ts:115:31
    at call (/_/httptoolkit-server/node_modules/connect/index.js:239:7)
    at next (/_/httptoolkit-server/node_modules/connect/index.js:183:5)
    at /_/httptoolkit-server/node_modules/mockttp/src/util/request-utils.ts:317:5
    at call (/_/httptoolkit-server/node_modules/connect/index.js:239:7)
    at next (/_/httptoolkit-server/node_modules/connect/index.js:183:5)
    at Function.handle (/_/httptoolkit-server/node_modules/connect/index.js:186:3)
    at Server.app (/_/httptoolkit-server/node_modules/connect/index.js:51:37)
    at Server.emit (events.js:314:20)
    at Server.EventEmitter.emit (domain.js:486:12)
    at parserOnIncoming (_http_server.js:863:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at socketOnData (_http_server.js:581:22)`

The upstream is python xmlrpclib, I cannot capture its traffic successfully.

**Comment by pimterry** [comment]
I'm not clear why this is a valid URL. The RFC3986 spec says:

> IPv6 (and later) literals have been added to the list of possible identifiers for the host portion of an authority component, as described by RFC2732, with the addition of "[" and "]" to the reserved set and a version flag to anticipate future versions of IP literals. **Square brackets are now specified as reserved within the authority component and are not allowed outside their use as delimiters for an IP literal within host**.

`localhost:8123` is not an IP literal. As far as I can see, square brackets are only allowed for IPv6 raw IP addresses, e.g. `http://[::1]:7123`. I've just tested, and intercepting IPv6 address like those does work correctly.

Could you tell me any more about this URL? Is it coming from another tool, and working correctly for you elsewhere? Do the square brackets signify that IPv6 should be used in this case too, or something else?

**Comment by Parahexen** [comment]
```
3.2.2.  Host

   The host subcomponent of authority is identified by an IP literal
   encapsulated within square brackets, an IPv4 address in dotted-
   decimal form, **or a registered name**. 
```

**Comment by pimterry** [comment]
I don't understand - the text you quote says an IP literal can be enclosed in square brackets, but a registered name cannot. The ABNF listed below confirms that:

       host        = IP-literal / IPv4address / reg-name
       IP-literal = "[" ( IPv6address / IPvFuture  ) "]"
       IPvFuture  = "v" 1*HEXDIG "." 1*( unreserved / sub-delims / ":" )

Square brackets are only allowed around a literal IPv6 address (`::1`, or a full address like `2001:0db8:85a3:0000:0000:8a2e:0370:7334`) or the (AFAIK unused) `v...` versioned future IP address syntax. `localhost` is neither of those.

What am I missing?

(Also, `localhost:8123` isn't a registered name - `localhost` is. Registered names can't contain `:`, so I assume 8123 is the port?)

You're right in practice that the error here is coming from Node's parsing, so if there is a bug that's where it'd be, but I'm still not clear that this is a bug. Where did this URL come from?

**Comment by Parahexen** [comment]
I'm locating the problem upstream in python xmlrpclib.
Yes, 8123 is the port number.

**Comment by pimterry** [comment]
Any updates on this @Parahexen? Did you trace down the issue to xmlrpclib, or find out any more about where this URL is coming from?

**Comment by Parahexen** [comment]
Not yet, but I think it's nothing to do with mockttp but httptoolkit-server.

capture traffic to localhost:8000:
`Frame 8: 58 bytes on wire (464 bits), 58 bytes captured (464 bits) on interface lo0, id 0
Null/Loopback
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 51338, Dst Port: 8000, Seq: 37, Ack: 1, Len: 2
[2 Reassembled TCP Segments (38 bytes): #7(36), #8(2)]
Hypertext Transfer Protocol
    CONNECT localhost:8069:80 HTTP/1.0\r\n
        [Expert Info (Chat/Sequence): CONNECT localhost:8069:80 HTTP/1.0\r\n]
            [CONNECT localhost:8069:80 HTTP/1.0\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Method: CONNECT
        Request URI: localhost:8069:80
        Request Version: HTTP/1.0
    \r\n
    [HTTP request 1/1]
    [Response in frame: 11]
`

capture traffice to localhost:45456:
nothing while the error still printed out in httptoolkit-server's log.

**Comment by Parahexen** [comment]
Mhhhh...
Seems the final criminal is python's http.client:
https://github.com/python/cpython/blob/master/Lib/http/client.py
```
                    # As per RFC 273, IPv6 address should be wrapped with []
                    # when used as Host header

                    if host.find(':') >= 0:
                        host_enc = b'[' + host_enc + b']'
```

1. httptoolkit-server python hacks set a tunnel by this:
```
# Redirect and then tunnel all plain HTTP connections:
_http_connection_init = HTTPConnection.__init__
@functools.wraps(_http_connection_init)
def _new_http_connection_init(self, host, port=80, *k, **kw):
    _http_connection_init(self, _proxyHost, int(_proxyPort), *k, **kw)
    self.set_tunnel(host, port)
HTTPConnection.__init__ = _new_http_connection_init
```
where `_proxyHost=127.0.0.1` and `_proxyPort=8000`, `host=localhost:8069` and `port=80`.

2. http.client is indeed followed RFC3986 I think, but it assumed that a tunnel host should not be like this and expecting a pure ip address or domain name without additional port number, so its check/fix procedures are not work on this:
```
    def set_tunnel(self, host, port=None, headers=None):
        ...
        self._tunnel_host, self._tunnel_port = self._get_hostport(host, port)
        ...
    def _get_hostport(self, host, port):
        if port is None:
            ...
        return (host, port)
```

3. Next, http.client added the brackets to the `localhost:8069` because it think it's an ipv6 address by the colon. Then, it packed the processed request into the proxy data.

4. Finally node took the last stand and blocked the further error spreading.

So, I think the hack has a bit flaw there.
It's a tricky debugging tour took me 3 hours. XD

**Comment by pimterry** [comment]
Great find, that's really interesting! Yes, agreed, that's clearly a bug. Looking closely at [the docs](https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection), it's recommended that `host` is the host and `port` the port, so those values are separated, but

> If no port number is passed, the port is extracted from the host string if it has the form host:port

`set_tunnel` has the same logic internally, but because we default the port to `80`, `port is None` is always false, and we never actually use that logic, and we end up with a broken hostname (it sounds like you've already worked this out, just writing it out fully here for my own reference).

Fortunately this looks like an easy fix. Do you want to take a quick shot at fixing it yourself? I think it's probably just a matter of changing `port=80` to `port=None` in the HTTP Toolkit Python override script (and the `httplib.py` override too) and then testing it in a few cases (including your own!) to make sure that works nicely everywhere. Notably, HTTP Toolkit contributors get [free HTTP Toolkit Pro](https://github.com/httptoolkit/httptoolkit#contributing-directly) :smile:. No pressure if you're busy, I'll hopefully have some time to look at this soon either way.

In the meantime, I'm going to move this to the general HTTP Toolkit feedback repo, since it's not a Mockttp-specific issue.
