### ISSUE TITLE
Issue with latest version of jest with the jsdom environment

### ISSUE THREAD

**Issue by roberttaylor426** [httptoolkit/mockttp#58]
Hi,

Not so long ago the Jest folks [removed setImmediate and clearImmediate from the jsdom environment](https://github.com/facebook/jest/pull/11222/files).

Having upgraded to the latest version of Jest and set `testEnvironment` to `jsdom` I am now seeing:

```
ReferenceError: setImmediate is not defined

import { getLocal } from 'mockttp';
^

      at Object.<anonymous> (node_modules/vm2/lib/main.js:1277:2)                                                                           
      at Object.<anonymous> (node_modules/vm2/index.js:3:18)                                                                                
      at Object.<anonymous> (node_modules/degenerator/src/index.ts:6:1)                                                                     
      at Object.<anonymous> (node_modules/pac-resolver/src/index.ts:3:1)                                                                    
      at Object.<anonymous> (node_modules/pac-proxy-agent/src/agent.ts:13:1)                                                                
      at Object.<anonymous> (node_modules/pac-proxy-agent/src/index.ts:8:1)                                                                 
      at Object.<anonymous> (node_modules/proxy-agent/index.js:16:21)                                                                       
      at Object.<anonymous> (node_modules/mockttp/src/util/http-agents.ts:3:1)                                                              
      at Object.<anonymous> (node_modules/mockttp/src/rules/requests/request-handlers.ts:54:1)                                              
      at Object.<anonymous> (node_modules/mockttp/src/rules/requests/request-rule-builder.ts:7:1)
```

Is there a suggested solution for this? Do I need to polyfill `setImmediate`?

Thanks!

**Comment by roberttaylor426** [comment]
Once [npm is available again](https://status.npmjs.org/incidents/7pqfqvkwvb58?u=9ls83ts9v472) I'll try to pull together a simple example project.

In the meantime here's my package.json jest config:

```
"jest": {
        "moduleNameMapper": {
            "\\.(jpg|ico|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/test/fileMock.js",
            "\\.(css|less)$": "<rootDir>/test/fileMock.js"
        },
        "roots": [
            "<rootDir>"
        ],
        "transform": {
            "^.+\\.tsx?$": "ts-jest"
        },
        "testMatch": [
            "<rootDir>/test/**/*test.ts",
            "<rootDir>/test/**/*test.tsx"
        ],
        "moduleFileExtensions": [
            "ts",
            "tsx",
            "js",
            "jsx",
            "json"
        ],
        "setupFilesAfterEnv": [
            "<rootDir>/jest.setup.ts"
        ],
        "testEnvironment": "jsdom"
    }
```

I'm running `npx jest`, and I'm using webpack with babel-loader (and @babel/preset-typescript) if that helps.
